runtime: python39  # Python runtime, but could be any runtime

handlers:
- url: /(.+)  # This will match all URLs
  static_files: \1  # Serve static files from the root directory
  upload: (.*)  # Match any file extension
